# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Microsoft.Gaming.GDK
PackageVersion: 2510.0.5339
MinimumOSVersion: 10.0.17763.0
Scope: machine
InstallerSwitches:
  Silent: /q
  SilentWithProgress: /q
AppsAndFeaturesEntries:
- DisplayName: Microsoft Game Development Kit - 251000 (October 2025)
  DisplayVersion: 10.1.26100.5339
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: burn
  NestedInstallerFiles:
  - RelativeFilePath: PGDK.exe
  InstallerUrl: https://github.com/microsoft/GDK/releases/download/October-2025-v2510.0.5339/GDK_2510.0.5339.zip
  InstallerSha256: EF24D32078FF37FEC5581A136B59A3822A9CD84C08E340BC1D75235138428C7E
  ProductCode: '{3fe71d85-4c45-4278-b562-ee517679e775}'
ManifestType: installer
ManifestVersion: 1.6.0